package edu.ntu.arbor.sbchao.androidlogger.scheme;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import edu.ntu.arbor.sbchao.androidlogger.scheme.MobileLog;
import edu.ntu.arbor.sbchao.androidlogger.scheme.NetworkLog;

import edu.ntu.arbor.sbchao.androidlogger.scheme.MobileLogDao;
import edu.ntu.arbor.sbchao.androidlogger.scheme.NetworkLogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mobileLogDaoConfig;
    private final DaoConfig networkLogDaoConfig;

    private final MobileLogDao mobileLogDao;
    private final NetworkLogDao networkLogDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mobileLogDaoConfig = daoConfigMap.get(MobileLogDao.class).clone();
        mobileLogDaoConfig.initIdentityScope(type);

        networkLogDaoConfig = daoConfigMap.get(NetworkLogDao.class).clone();
        networkLogDaoConfig.initIdentityScope(type);

        mobileLogDao = new MobileLogDao(mobileLogDaoConfig, this);
        networkLogDao = new NetworkLogDao(networkLogDaoConfig, this);

        registerDao(MobileLog.class, mobileLogDao);
        registerDao(NetworkLog.class, networkLogDao);
    }
    
    public void clear() {
        mobileLogDaoConfig.getIdentityScope().clear();
        networkLogDaoConfig.getIdentityScope().clear();
    }

    public MobileLogDao getMobileLogDao() {
        return mobileLogDao;
    }

    public NetworkLogDao getNetworkLogDao() {
        return networkLogDao;
    }

}
