package edu.ntu.arbor.sbchao.androidlogger.scheme;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACTIVITY_LOG.
 */
public class ActivityLog {

    private Long id;
    /** Not-null value. */
    private String deviceId;
    /** Not-null value. */
    private java.util.Date startTime;
    /** Not-null value. */
    private java.util.Date endTime;
    /** Not-null value. */
    private String activityName;

    public ActivityLog() {
    }

    public ActivityLog(Long id) {
        this.id = id;
    }

    public ActivityLog(Long id, String deviceId, java.util.Date startTime, java.util.Date endTime, String activityName) {
        this.id = id;
        this.deviceId = deviceId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.activityName = activityName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDeviceId() {
        return deviceId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /** Not-null value. */
    public java.util.Date getStartTime() {
        return startTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    /** Not-null value. */
    public java.util.Date getEndTime() {
        return endTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
    }

    /** Not-null value. */
    public String getActivityName() {
        return activityName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

}
