package edu.ntu.arbor.sbchao.androidlogger.scheme;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOBILE_LOG.
 */
public class MobileLog {

    private Long id;
    /** Not-null value. */
    private String deviceId;
    /** Not-null value. */
    private java.util.Date time;
    private int dayOfWeek;
    private int hourOfDay;
    private int recordFreq;
    private int batStatus;
    private double batPct;
    private int gpsStatus;
    private int networkStatus;
    /** Not-null value. */
    private String wifiState;
    /** Not-null value. */
    private String mobileState;
    /** Not-null value. */
    private String processCurrentPackage;
    private boolean isLowMemory;
    private Double locAcc;
    private Double lat;
    private Double lon;
    private String locProvider;
    private Double speed;

    public MobileLog() {
    }

    public MobileLog(Long id) {
        this.id = id;
    }

    public MobileLog(Long id, String deviceId, java.util.Date time, int dayOfWeek, int hourOfDay, int recordFreq, int batStatus, double batPct, int gpsStatus, int networkStatus, String wifiState, String mobileState, String processCurrentPackage, boolean isLowMemory, Double locAcc, Double lat, Double lon, String locProvider, Double speed) {
        this.id = id;
        this.deviceId = deviceId;
        this.time = time;
        this.dayOfWeek = dayOfWeek;
        this.hourOfDay = hourOfDay;
        this.recordFreq = recordFreq;
        this.batStatus = batStatus;
        this.batPct = batPct;
        this.gpsStatus = gpsStatus;
        this.networkStatus = networkStatus;
        this.wifiState = wifiState;
        this.mobileState = mobileState;
        this.processCurrentPackage = processCurrentPackage;
        this.isLowMemory = isLowMemory;
        this.locAcc = locAcc;
        this.lat = lat;
        this.lon = lon;
        this.locProvider = locProvider;
        this.speed = speed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDeviceId() {
        return deviceId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /** Not-null value. */
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public int getDayOfWeek() {
        return dayOfWeek;
    }

    public void setDayOfWeek(int dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    public int getHourOfDay() {
        return hourOfDay;
    }

    public void setHourOfDay(int hourOfDay) {
        this.hourOfDay = hourOfDay;
    }

    public int getRecordFreq() {
        return recordFreq;
    }

    public void setRecordFreq(int recordFreq) {
        this.recordFreq = recordFreq;
    }

    public int getBatStatus() {
        return batStatus;
    }

    public void setBatStatus(int batStatus) {
        this.batStatus = batStatus;
    }

    public double getBatPct() {
        return batPct;
    }

    public void setBatPct(double batPct) {
        this.batPct = batPct;
    }

    public int getGpsStatus() {
        return gpsStatus;
    }

    public void setGpsStatus(int gpsStatus) {
        this.gpsStatus = gpsStatus;
    }

    public int getNetworkStatus() {
        return networkStatus;
    }

    public void setNetworkStatus(int networkStatus) {
        this.networkStatus = networkStatus;
    }

    /** Not-null value. */
    public String getWifiState() {
        return wifiState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWifiState(String wifiState) {
        this.wifiState = wifiState;
    }

    /** Not-null value. */
    public String getMobileState() {
        return mobileState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMobileState(String mobileState) {
        this.mobileState = mobileState;
    }

    /** Not-null value. */
    public String getProcessCurrentPackage() {
        return processCurrentPackage;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProcessCurrentPackage(String processCurrentPackage) {
        this.processCurrentPackage = processCurrentPackage;
    }

    public boolean getIsLowMemory() {
        return isLowMemory;
    }

    public void setIsLowMemory(boolean isLowMemory) {
        this.isLowMemory = isLowMemory;
    }

    public Double getLocAcc() {
        return locAcc;
    }

    public void setLocAcc(Double locAcc) {
        this.locAcc = locAcc;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

    public String getLocProvider() {
        return locProvider;
    }

    public void setLocProvider(String locProvider) {
        this.locProvider = locProvider;
    }

    public Double getSpeed() {
        return speed;
    }

    public void setSpeed(Double speed) {
        this.speed = speed;
    }

}
