package edu.ntu.arbor.sbchao.androidlogger.scheme;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NETWORK_LOG.
 */
public class NetworkLog {

    private Long id;
    /** Not-null value. */
    private String deviceId;
    /** Not-null value. */
    private java.util.Date time;
    private int dayOfWeek;
    private int hourOfDay;
    private int recordFreq;
    /** Not-null value. */
    private String mobileState;
    /** Not-null value. */
    private String wifiState;
    private long transmittedByte;
    private long receivedByte;
    /** Not-null value. */
    private String appName;
    private boolean isUsing;

    public NetworkLog() {
    }

    public NetworkLog(Long id) {
        this.id = id;
    }

    public NetworkLog(Long id, String deviceId, java.util.Date time, int dayOfWeek, int hourOfDay, int recordFreq, String mobileState, String wifiState, long transmittedByte, long receivedByte, String appName, boolean isUsing) {
        this.id = id;
        this.deviceId = deviceId;
        this.time = time;
        this.dayOfWeek = dayOfWeek;
        this.hourOfDay = hourOfDay;
        this.recordFreq = recordFreq;
        this.mobileState = mobileState;
        this.wifiState = wifiState;
        this.transmittedByte = transmittedByte;
        this.receivedByte = receivedByte;
        this.appName = appName;
        this.isUsing = isUsing;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDeviceId() {
        return deviceId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /** Not-null value. */
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public int getDayOfWeek() {
        return dayOfWeek;
    }

    public void setDayOfWeek(int dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    public int getHourOfDay() {
        return hourOfDay;
    }

    public void setHourOfDay(int hourOfDay) {
        this.hourOfDay = hourOfDay;
    }

    public int getRecordFreq() {
        return recordFreq;
    }

    public void setRecordFreq(int recordFreq) {
        this.recordFreq = recordFreq;
    }

    /** Not-null value. */
    public String getMobileState() {
        return mobileState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMobileState(String mobileState) {
        this.mobileState = mobileState;
    }

    /** Not-null value. */
    public String getWifiState() {
        return wifiState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWifiState(String wifiState) {
        this.wifiState = wifiState;
    }

    public long getTransmittedByte() {
        return transmittedByte;
    }

    public void setTransmittedByte(long transmittedByte) {
        this.transmittedByte = transmittedByte;
    }

    public long getReceivedByte() {
        return receivedByte;
    }

    public void setReceivedByte(long receivedByte) {
        this.receivedByte = receivedByte;
    }

    /** Not-null value. */
    public String getAppName() {
        return appName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    public boolean getIsUsing() {
        return isUsing;
    }

    public void setIsUsing(boolean isUsing) {
        this.isUsing = isUsing;
    }

}
